// Standalone entry: `node examples/fastify-sqlite/index.ts`.
//
// Zero-setup path: signing key + consent secret are loaded-or-generated by the
// quickstart helper (§17.8) into ${MCP_SSO_DIR}/.mcp-sso (0700/0600 + .gitignore);
// identity is console pairing (§17.5) — an operator pastes a one-time code from
// this console; audit events stream to ${dir}/audit.jsonl. NO signing/consent env
// config is required. Override issuer/resource/port via env for a real deployment
// (then provide https URLs and drop the loopback dev flag — see isLoopback below).

import { join } from "node:path";
import { createBridgeConfig } from "../../src/config.ts";
import { JsonlFileAudit } from "../../src/audit/jsonl-file.ts";
import { loadOrCreateQuickstartSecrets } from "../../src/quickstart.ts";
import { createConsolePairingIdentity } from "../../src/identity/console-pairing.ts";
import { buildApp } from "./app.ts";

const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]"]);
function isLoopback(url: string): boolean {
  try { return LOOPBACK_HOSTS.has(new URL(url).hostname); } catch { return false; }
}
function listEnv(k: string, def: string): string[] {
  return (process.env[k] ?? def).split(",").map((s) => s.trim()).filter(Boolean);
}

async function main(): Promise<void> {
  const dir = process.env.MCP_SSO_DIR ?? "./.mcp-sso";
  const secrets = await loadOrCreateQuickstartSecrets({ dir });

  const port = Number(process.env.PORT ?? 3000);
  const issuer = process.env.OAUTH_ISSUER ?? `http://localhost:${port}`;
  const resource = process.env.OAUTH_RESOURCE ?? `http://localhost:${port}/mcp`;
  const config = createBridgeConfig({
    issuer,
    resource,
    consentSigningSecret: secrets.consentSigningSecret,
    signingPrivateJwk: secrets.signingPrivateJwk,
    redirectAllowlist: listEnv("OAUTH_REDIRECT_ALLOWLIST", ""),
    scopeCatalog: listEnv("OAUTH_SCOPE_CATALOG", "mcp:read,mcp:write"),
    defaultScopes: listEnv("OAUTH_DEFAULT_SCOPES", "mcp:read"),
    allowedOrigins: listEnv("OAUTH_ALLOWED_ORIGINS", issuer),
    dcr: { mode: "stateless" },
    // Loopback → permit http (Claude Code expects http://localhost). A real
    // (non-loopback) deployment must be https and gets no dev flag.
    dev: isLoopback(issuer) ? { allowInsecureLocalhost: true } : undefined,
    accessTokenTtlSeconds: 600,
    refreshTokenTtlSeconds: 2_592_000,
    consentTokenTtlSeconds: 300,
    authorizationCodeTtlSeconds: 300,
  });

  const auditLog = join(dir, "audit.jsonl");
  const audit = new JsonlFileAudit(auditLog);
  const pairing = createConsolePairingIdentity({ audit });

  // Persist OAuth state (refresh-token families, consent JTIs, auth codes) across
  // restarts alongside the quickstart secrets — default to a file in the quickstart
  // dir (covered by its `*` .gitignore); OAUTH_SQLITE_FILE overrides.
  const sqliteFile = process.env.OAUTH_SQLITE_FILE ?? join(dir, "auth.db");
  const { app } = await buildApp({ config, pairing, audit, sqliteFile });
  await app.listen({ port, host: "0.0.0.0" });
  console.error(`mcp-sso example listening on :${port}`);
  console.error(`  issuer=${config.issuer}  resource=${config.resource}`);
  console.error(`  secrets dir: ${dir}   (quickstart §17.8; 0700/0600 + .gitignore)`);
  console.error(`  audit log:  ${auditLog}`);
  console.error(`  Point an MCP client at ${config.resource}; the pairing code prints here on first authorize.`);
}

main().catch((error) => { console.error(error); process.exit(1); });
