// Standalone entry: `node examples/fastify-sqlite/index.ts`.
//
// Two paths, selected by env — NOT a routing of one into the other:
//
//  - PRODUCTION (Cloudflare Access): when CF_ACCESS_AUDIENCE is set, the bridge
//    uses env-configured signing material + the Cloudflare Access identity port
//    (header-injected by CF). This is the documented production startup.
//
//  - ZERO-SETUP (console pairing): otherwise, signing key + consent secret are
//    loaded-or-generated by the quickstart helper (§17.8) and identity is console
//    pairing (§17.5) — an operator pastes a one-time code from the console. NO
//    signing/consent env config is required. Replaces the old DEV_STUB_SUBJECT
//    dev bypass (a real gate, not a no-op).
//
// Both paths stream audit events to ${dir}/audit.jsonl and persist OAuth state to
// ${dir}/auth.db.

import { join } from "node:path";
import { createBridgeConfig } from "../../src/config.ts";
import { JsonlFileAudit } from "../../src/audit/jsonl-file.ts";
import { loadOrCreateQuickstartSecrets } from "../../src/quickstart.ts";
import { createCloudflareAccessIdentity } from "../../src/identity/cloudflare-access.ts";
import { buildApp, configFromEnv } from "./app.ts";

const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]"]);
function isLoopback(url: string): boolean {
  try { return LOOPBACK_HOSTS.has(new URL(url).hostname); } catch { return false; }
}
function listEnv(k: string, def: string): string[] {
  return (process.env[k] ?? def).split(",").map((s) => s.trim()).filter(Boolean);
}
function mustEnv(k: string): string { const v = process.env[k]; if (!v) throw new Error(`Missing env: ${k}`); return v; }

async function main(): Promise<void> {
  const dir = process.env.MCP_SSO_DIR ?? "./.mcp-sso";
  const sqliteFile = process.env.OAUTH_SQLITE_FILE ?? join(dir, "auth.db");
  const audit = new JsonlFileAudit(join(dir, "audit.jsonl"));
  const port = Number(process.env.PORT ?? 3000);

  if (process.env.CF_ACCESS_AUDIENCE) {
    // PRODUCTION: Cloudflare Access (the documented startup) + env signing material.
    const config = configFromEnv();
    const identity = createCloudflareAccessIdentity({
      audience: mustEnv("CF_ACCESS_AUDIENCE"),
      certsUrl: mustEnv("CF_ACCESS_CERTS_URL"),
      issuer: mustEnv("CF_ACCESS_ISSUER"),
      emailAllowlist: listEnv("CF_ACCESS_EMAIL_ALLOWLIST", ""),
    });
    const { app } = await buildApp({ config, identity, audit, sqliteFile });
    await listen(app, port, config, "Cloudflare Access");
    return;
  }

  // ZERO-SETUP: quickstart secrets + console pairing.
  const secrets = await loadOrCreateQuickstartSecrets({ dir });
  const issuer = process.env.OAUTH_ISSUER ?? `http://localhost:${port}`;
  const resource = process.env.OAUTH_RESOURCE ?? `http://localhost:${port}/mcp`;
  const config = createBridgeConfig({
    issuer,
    resource,
    consentSigningSecret: secrets.consentSigningSecret,
    signingPrivateJwk: secrets.signingPrivateJwk,
    redirectAllowlist: listEnv("OAUTH_REDIRECT_ALLOWLIST", ""),
    scopeCatalog: listEnv("OAUTH_SCOPE_CATALOG", "mcp:read,mcp:write"),
    defaultScopes: listEnv("OAUTH_DEFAULT_SCOPES", "mcp:read"),
    allowedOrigins: listEnv("OAUTH_ALLOWED_ORIGINS", issuer),
    dcr: { mode: "stateless" },
    dev: isLoopback(issuer) ? { allowInsecureLocalhost: true } : undefined,
    accessTokenTtlSeconds: 600,
    refreshTokenTtlSeconds: 2_592_000,
    consentTokenTtlSeconds: 300,
    authorizationCodeTtlSeconds: 300,
  });
  // Pairing options only — buildApp constructs the identity and wires `audit` into
  // it, so pairing events reach the same sink as the Bridge/RequestAuthorizer.
  const { app } = await buildApp({ config, pairing: {}, audit, sqliteFile });
  await listen(app, port, config, "console pairing");
}

async function listen(app: { listen(opts: { port: number; host: string }): Promise<unknown> }, port: number, config: { issuer: string; resource: string }, mode: string): Promise<void> {
  await app.listen({ port, host: "0.0.0.0" });
  console.error(`mcp-sso example listening on :${port}  (identity: ${mode})`);
  console.error(`  issuer=${config.issuer}  resource=${config.resource}`);
}

main().catch((error) => { console.error(error); process.exit(1); });
